apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: demo-app
  labels:
    grafana_datasource: "1"
data:
  prometheus.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.demo-app.svc.cluster.local:9090
        isDefault: true

