apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: spring-boot-demo-pdb
  namespace: demo-app
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spring-boot-demo

