apiVersion: v1
kind: Secret
metadata:
  name: demo-app-db-secret
  namespace: demo-app
type: Opaque
stringData:
  # Replace values before applying or create secret with kubectl create secret generic
  POSTGRES_USER: demo
  POSTGRES_PASSWORD: demo
  JDBC_DATABASE_URL: jdbc:postgresql://postgres.demo-app.svc.cluster.local:5432/demo

