apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: demo-app
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'kubernetes-app'
        static_configs:
          - targets: ['spring-boot-demo.demo-app.svc.cluster.local:8080']
        metrics_path: /actuator/prometheus

