apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: demo-app
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    clients:
      - url: http://loki.demo-app.svc.cluster.local:3100/loki/api/v1/push

    positions:
      filename: /var/log/promtail_positions.yaml

    scrape_configs:
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            target_label: app
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
        pipeline_stages:
          - docker: {}
        static_configs:
          - targets: [localhost]
            labels:
              job: kubernetes-pods

