{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ default (printf "%s-ingress" (include "springboot.fullname" .)) .Values.ingress.name }}
  labels:
{{ include "springboot.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.app.name }}
{{- end }}
